package source;

import com.github.dhiraj072.randomwordgenerator.RandomWordGenerator;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class AutoGeneratedWordTest {

    public AutoGeneratedWord word;

    @BeforeEach
    void setUp() {
        word = new AutoGeneratedWord();
    }

    @Test
    void getWordSizeTest(){
        word.getWordSize();
    }

    @Test
    void getWordTest(){
        word.getWord();
    }

    @AfterEach
    void tearDown() {
    }
}