package source;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class HangmanTest {

    AutoGeneratedWord word;

    @BeforeEach
    void setUp() {
        word = new AutoGeneratedWord();
    }

    @Test
    void main(){
        word.generateNewWord();
        System.out.println(word.getWord());
    }

    @AfterEach
    void tearDown() {
    }
}