package source;

public class Hangman {
    public static void main( String[] args){
        AutoGeneratedWord word = new AutoGeneratedWord();
        word.generateNewWord();
        System.out.println(word.getWord());
    }
}
